## Problem

$$f(w_1, w_2) = 0.1w_1^2 + 2w_2^2 \;\;\;\;\;\;\;(1)$$

In [5]:
import numpy as np

### RMSprop

In [1]:
def df_w(W):
    """
    Thực hiện tính gradient của dw1 và dw2
    Arguments:
    W -- np.array [w1, w2]
    Returns:
    dW -- np.array [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    """
    #################### YOUR CODE HERE ####################
    w1, w2 = W
    dw1 = 0.2 * w1 
    dw2 = 4 * w2 
    dW = np.array([dw1, dw2])
    ########################################################
    return dW

In [2]:
def RMSProp(W, dW, lr, S, gamma):
    """
    Thực hiện thuật tóan RMSProp để update w1 và w2
    Arguments:
    W -- np.array: [w1, w2]
    dW -- np.array: [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    lr -- float: learning rate
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients
    gamma -- float: hệ số long-range average
    Returns:
    W -- np.array: [w1, w2] w1 và w2 sau khi đã update
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients sau khi đã cập nhật
    """
    epsilon = 1e-6
    #################### YOUR CODE HERE ####################

    S = gamma * S + (1 - gamma) * (dW ** 2)
    W = W - lr * dW / (np.sqrt(S) + epsilon)
    ########################################################
    return W, S

In [8]:
def train_p1(optimizer, lr, epochs):
    """
    Thực hiện tìm điểm minimum của function (1) dựa vào thuật toán
    được truyền vào từ optimizer
    Arguments:
    optimize : function thực hiện thuật toán optimization cụ thể
    lr -- float: learning rate
    epochs -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """
    # initial
    W = np.array([-5, -2], dtype=np.float32)
    S = np.array([0, 0], dtype=np.float32)
    results = [W]
    #################### YOUR CODE HERE ####################
    # Tạo vòng lặp theo số lần epochs
    # tìm gradient dW gồm dw1 và dw2
    # dùng thuật toán optimization cập nhật w1, w2, s1, s2
    # append cặp [w1, w2] vào list results
    for epoch in range(epochs):
    # Tính gradient tại W hiện tại
        dW = df_w(W)
        W, S = optimizer(W, dW, lr, S, gamma=0.9)
        # Lưu kết quả vào danh sách
        results.append(W.copy())

    ########################################################
    return results

In [9]:
train_p1(RMSProp, lr=0.3, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.0513197 , -1.05131708]),
 array([-3.43519553, -0.59152376]),
 array([-2.95893489, -0.3294397 ]),
 array([-2.56546089, -0.17756504]),
 array([-2.22920358, -0.09163272]),
 array([-1.93626564, -0.04494508]),
 array([-1.67817504, -0.02081429]),
 array([-1.44934809, -0.00903562]),
 array([-1.24588029, -0.00364592]),
 array([-1.06490135, -0.00135352]),
 array([-9.04200650e-01, -4.56447225e-04]),
 array([-7.61994932e-01, -1.37563947e-04]),
 array([-6.36776983e-01, -3.62604278e-05]),
 array([-5.27213771e-01, -8.11346375e-06]),
 array([-4.32077091e-01, -1.47475425e-06]),
 array([-3.50197152e-01, -2.02787524e-07]),
 array([-2.80433359e-01, -1.84235524e-08]),
 array([-2.21658617e-01, -7.67771777e-10]),
 array([-1.72754375e-01,  7.80432778e-12]),
 array([-1.32614084e-01, -5.05777072e-13]),
 array([-1.00152823e-01,  6.19098174e-14]),
 array([-7.43209130e-02, -1.13368674e-14]),
 array([-5.41193712e-02,  2.80153177e-15]),
 array([-3.86152607e-02, -8.81296